# Generated by Django 6.0.3 on 2026-05-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_menuitem_tablereservation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tablereservation',
            name='guests',
            field=models.CharField(choices=[('1', '1 человек'), ('2', '2 человека'), ('3-4', '3-4 человека'), ('5-6', '5-6 человек'), ('7+', '7+')], max_length=10),
        ),
        migrations.AlterField(
            model_name='tablereservation',
            name='zone',
            field=models.CharField(choices=[('hall', 'В зале'), ('window', 'У окна'), ('terrace', 'На террасе')], max_length=20),
        ),
    ]
