# Generated by Django 6.0.3 on 2026-05-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_tablereservation_guests_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='orderitem',
            name='menu_item_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
